/**
 * Export Utilities
 * Provides functionality to export and share comparison results
 */

import { ComparisonResult } from '../types';

/**
 * Formats comparison result as plain text
 */
export function formatAsText(prompt: string, result: ComparisonResult): string {
  const timestamp = new Date().toISOString();

  return `
LLM Training Lab - Comparison Result
====================================
Generated: ${timestamp}

PROMPT:
${prompt}

---

SFT MODEL RESPONSE (Mimicry):
${result.sftResponse}

---

RL-ALIGNED MODEL RESPONSE:
${result.rlResponse}

---

ANALYSIS:
${result.analysis}

---
Generated by LLM Training Lab: From Pretraining to RL
https://github.com/djimit/LLM-Training-Lab-From-Pretraining-to-RL
  `.trim();
}

/**
 * Formats comparison result as Markdown
 */
export function formatAsMarkdown(prompt: string, result: ComparisonResult): string {
  const timestamp = new Date().toISOString();

  return `
# LLM Training Lab - Comparison Result

*Generated: ${timestamp}*

## Prompt

> ${prompt}

---

## SFT Model Response (Mimicry)

${result.sftResponse}

---

## RL-Aligned Model Response

${result.rlResponse}

---

## Analysis

*${result.analysis}*

---

*Generated by [LLM Training Lab](https://github.com/djimit/LLM-Training-Lab-From-Pretraining-to-RL)*
  `.trim();
}

/**
 * Formats comparison result as JSON
 */
export function formatAsJson(prompt: string, result: ComparisonResult): string {
  return JSON.stringify({
    timestamp: new Date().toISOString(),
    prompt,
    sftResponse: result.sftResponse,
    rlResponse: result.rlResponse,
    analysis: result.analysis,
    source: 'LLM Training Lab'
  }, null, 2);
}

/**
 * Downloads content as a file
 */
export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.style.display = 'none';

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  // Clean up the URL object
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

/**
 * Exports comparison as text file
 */
export function exportAsText(prompt: string, result: ComparisonResult): void {
  const content = formatAsText(prompt, result);
  const timestamp = new Date().toISOString().slice(0, 10);
  downloadFile(content, `llm-comparison-${timestamp}.txt`, 'text/plain');
}

/**
 * Exports comparison as Markdown file
 */
export function exportAsMarkdown(prompt: string, result: ComparisonResult): void {
  const content = formatAsMarkdown(prompt, result);
  const timestamp = new Date().toISOString().slice(0, 10);
  downloadFile(content, `llm-comparison-${timestamp}.md`, 'text/markdown');
}

/**
 * Exports comparison as JSON file
 */
export function exportAsJson(prompt: string, result: ComparisonResult): void {
  const content = formatAsJson(prompt, result);
  const timestamp = new Date().toISOString().slice(0, 10);
  downloadFile(content, `llm-comparison-${timestamp}.json`, 'application/json');
}

/**
 * Copies content to clipboard
 */
export async function copyToClipboard(content: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(content);
    return true;
  } catch {
    // Fallback for older browsers
    try {
      const textarea = document.createElement('textarea');
      textarea.value = content;
      textarea.style.position = 'fixed';
      textarea.style.left = '-9999px';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      return true;
    } catch {
      return false;
    }
  }
}

/**
 * Generates a shareable URL (placeholder for future implementation)
 */
export function generateShareUrl(prompt: string, _result: ComparisonResult): string {
  // In a real implementation, this would create a shortened URL or save to a backend
  const encodedPrompt = encodeURIComponent(prompt.slice(0, 200));
  return `${window.location.origin}?prompt=${encodedPrompt}`;
}

/**
 * Prints the comparison result
 */
export function printComparison(prompt: string, result: ComparisonResult): void {
  const content = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>LLM Training Lab - Comparison</title>
      <style>
        body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
        h1 { color: #1e293b; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
        h2 { color: #334155; margin-top: 30px; }
        .prompt { background: #f1f5f9; padding: 15px; border-radius: 8px; font-style: italic; }
        .response { background: #fff; border: 1px solid #e2e8f0; padding: 15px; border-radius: 8px; margin: 10px 0; }
        .sft { border-left: 4px solid #a855f7; }
        .rl { border-left: 4px solid #10b981; }
        .analysis { background: #0f172a; color: #e2e8f0; padding: 15px; border-radius: 8px; font-style: italic; }
        .footer { margin-top: 30px; text-align: center; color: #94a3b8; font-size: 12px; }
        @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
      </style>
    </head>
    <body>
      <h1>LLM Training Lab - Comparison Result</h1>
      <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>

      <h2>Prompt</h2>
      <div class="prompt">${escapeHtmlForPrint(prompt)}</div>

      <h2>SFT Model Response (Mimicry)</h2>
      <div class="response sft">${escapeHtmlForPrint(result.sftResponse)}</div>

      <h2>RL-Aligned Model Response</h2>
      <div class="response rl">${escapeHtmlForPrint(result.rlResponse)}</div>

      <h2>Analysis</h2>
      <div class="analysis">${escapeHtmlForPrint(result.analysis)}</div>

      <div class="footer">
        Generated by LLM Training Lab: From Pretraining to RL
      </div>
    </body>
    </html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(content);
    printWindow.document.close();
    printWindow.print();
  }
}

/**
 * Escapes HTML for print output
 */
function escapeHtmlForPrint(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
    .replace(/\n/g, '<br>');
}
